### PR TITLE
Fix of Issue #243

### LINKED ISSUE #243: bitbucket: update package.json with correct license_url
Bitbucket issue `#22` (priority: trivial)
https://bitbucket.org/greenelab/adage-server/issues/22/update-packagejson-with-correct

The license_url location will change once we migrate the source to GitHub.

### PR DESCRIPTION
**Pull request by dongbohu**
This PR is to fix #243.

### CODE REVIEW

**Comment by rzelayafavila** [comment]
Hmmm, looks like something funky happened with the elasticsearch connection when running the tests in circleci though. Is this one of those things that happens sporadically with elasticsearch? Shall we click rebuild or is it a larger issue than that?

**Comment by dongbohu** [comment]
This does happen sometimes. Let's give it a little more time.

**Comment by dongbohu** [comment]
I am rebuilding it.

**Comment by rzelayafavila** [comment]
@dongbohu - what do you mean a little more time? Does it restart on its own if it failed?

**Comment by rzelayafavila** [comment]
@dongbohu - ok, sounds good.

**Comment by mhuyck** [comment]
Yay! Thank you @dongbohu.

**Pull request merged**
