### PR TITLE
Creating 'Help' page, which will contain documentation on what Genes, Samples, Experiments and Nodes are in adage, and how they relate to each other.

### PR DESCRIPTION
**Pull request by rzelayafavila**

### CODE REVIEW

**Comment by cgreene** [comment]
Also, I think this could get merged first and then @tj8901nm and @georgiadoing could craft the help language to be most suitable through a second PR against the template file.

**Comment by cgreene** [comment]
Also, we should cross-reference #47 here since that's the issue directly related to this.

**Comment by tj8901nm** [comment]
Yes, I agree that this can be merged first and the help language can be added in another PR.

**Comment by rzelayafavila** [comment]
@casey, @dongbohu, @tj8901nm : Ok, thanks! I only made one small change after it was approved, which was changing the id= attribute to the parent <div> instead of having it in the <span> tag (so we could get rid of those <span> tags). I will go ahead and merge.

**Pull request merged**
