### PR TITLE
Fix of issue #71: Highlight "GeneNetwork" tab when network is shown

### PR DESCRIPTION
**Pull request by dongbohu**
This is a fix of issue #71. 

There are a few ways to solve this problem. The one I chose is the simplest but may not be the best. According to the ui-router doc, the best seems to be create a parent state of `gene`, then make `gene_search` and `gene_network` the child states. But that will change at least three files, so I chose the current approach. I think it is a good hack to know.

### CODE REVIEW

**Comment by rzelayafavila** [comment]
Great! Would you have a url to a live version of this to check out in a web browser?

**Comment by dongbohu** [comment]
I found a bug in my fix. Let me work on it now.

**Comment by dongbohu** [comment]
I will let you guys know when it is ready.

**Comment by dongbohu** [comment]
I fixed the issue. Here is a demo site:
http://localhost/#/gene_network/?genes=10155
You can click other tabs (such as `Home`, `About`, etc) to test the highlight.

**Pull request merged**
