### PR TITLE
[FIX] Add a "clear all" button to analysis-detail

### LINKED ISSUE #248: Reviewer Request - clear analysis basket
Item from manuscript review:

"It would be convenient to add feature to clear analysis basket; samples remain in the basket unless they are individually removed or browser is refreshed."

We have a hard deadline on this - I think the feature is very fast to implement, but FYI:
"A decision will be made once we have received your revised manuscript, which we expect by 28 Sep 2017."

This timeline probably means that we need an implemented version ~2 weeks before that @mhuyck / @dongbohu

### PR DESCRIPTION
**Pull request by mhuyck**
This fixes #248 per reviewer request.

### CODE REVIEW

**Comment by mhuyck** [comment]
Working on a demo site...

**Comment by mhuyck** [comment]
Demo site running at: http://greenelab.fgtech.com

Deployment is currently failing during the Haystack indexing step, so the site above has an incomplete search index, but it should be good enough to see the way the "clear all" feature is implemented. Now filing an issue about the indexing...

**Comment by rzelayafavila** [comment]
Hmmm, for some reason I am having trouble accessing the demo site at http://greenelab.fgtech.com/ . Is anyone else having this problem?

**Comment by mhuyck** [comment]
Huh.. me too. Was working earlier. Let me see what's up.

**Comment by mhuyck** [comment]
Back up and running. I had changed something while debugging and it brought down the backend.

**Comment by rzelayafavila** [comment]
Gotcha @mhuyck , yep, it's working for me now as well - thanks!

**Pull request merged**
