### PR TITLE
empty readme; add codeclimate badge

### PR DESCRIPTION
**Pull request by cgreene**
Testing whether or not codeclimate works & adding the badge.

### CODE REVIEW

**Comment by cgreene** [comment]
Yea - codeclimate now checks pull requests. It's using the default since no codeclimate.yml file is configured. @gwaygenomics has been using this for automated testing. It's not always right but it helps to flag things that are worth considering & may save time by checking pep8 (once the pep8 checker is enabled).

**Comment by mhuyck** [comment]
Nice!

**Comment by dongbohu** [comment]
Should we merge this PR now or keep working on this **codeclimate-new-readme** branch?

**Comment by cgreene** [comment]
Whichever you prefer. Easy to merge and delete and then continue on readme
later. If it is time now to build a readme, feel free to continue on this.

**Comment by dongbohu** [comment]
I merged the PR and deleted this branch. Will add more contents in **README** later.

**Pull request merged**
