### PR TITLE
New service of constant: ActivityDigits

### PR DESCRIPTION
**Pull request by dongbohu**
This PR includes:

* Definition of a new constant service `ActivityDigits`, which is the number of digits after decimal point in activity values;

* Usage of this service in `high-range-exp` directive on **Node** page;

* Usage of this service on sample annotation values module.

### CODE REVIEW

**Comment by dongbohu** [comment]
By the way, this PR is for issue #86.

**Comment by mhuyck** [comment]
Nothing we can do about codeclimate's complaints here. (Aside: I have a gut feeling that the refactoring discussed in #76 would make for fewer redundant dependency lists and improve our score on that front.)

**Comment by dongbohu** [comment]
Thanks @mhuyck!

**Comment by dongbohu** [comment]
Just realized that the unit test doesn't need to provide the constant service explicitly. It will be found automatically by dependency injection.

**Pull request merged**
