### PR TITLE
Adding the migration that was missing for the 'analyze' app.

### PR DESCRIPTION
**Pull request by rzelayafavila**
Quick pull request - just adding the migration created by the makemigrations mgmt command. @dongbohu @mhuyck @cgreene

### CODE REVIEW

**Comment by mhuyck** [comment]
This is just the generated migration that comes after 0004, right? LGTM.

Anyone else notice that PR#5 is migration #0005?

**Comment by cgreene** [comment]
Probably didn't need to name all 3 of us, but I'll go ahead and approve for clarity :+1:

**Comment by mhuyck** [comment]
The UI here is definitely more cluttered than Bitbucket.

Go into the diff view and find the green "Review Changes" button. Clicking that brings up a menu that includes "approve."

**Comment by rzelayafavila** [comment]
Yep, totally, the interface is more cluttered than in bitbucket. Thanks everyone for approving! Also nice catch @mhuyck with the PR Number, I hadn't noticed that!

**Comment by cgreene** [comment]
Ok - thanks for the tip @mhuyck! I got it now. I agree that the number of features they added are a bit overwhelming.

**Pull request merged**
