### PR TITLE
Changing header of ParticipationType selector in signature page to read 'Filter genes in this signature by:'.

### PR DESCRIPTION
**Pull request by rzelayafavila**
This makes the meaning of it more obvious to new users. Example of this new UI is running at: http://165.123.67.154:8000/#/signature/100

### CODE REVIEW

**Comment by rzelayafavila** [comment]
Ok, thanks @dongbohu!

**Comment by cgreene** [comment]
I feel like this missed something @gwaygenomics said though.

**Comment by cgreene** [comment]
What was it? Something like:

Each signature is comprised of genes with various weights. Different methods find the most relevant set of genes. Filter genes in this signature by:

There was some additional value in being overly explanatory in this case, I think. Our users are not as familiar with these methods as we are.

**Comment by gwaygenomics** [comment]
> There was some additional value in being overly explanatory in this case, I think. Our users are not as familiar with these methods as we are.

💯

> Each signature is comprised of genes with various weights. Different methods find the most relevant set of genes. Filter genes in this signature by:

After chatting with @rzelayafavila it sounded like he was going to try adding some similar explanatory language. Although I do think `weights` can also be a bit confusing. How about

"Each signature is comprised of genes with varying importance. Different methods find the most relevant set of genes."  Then, in bold: **"Filter genes in this signature by:"**

**Comment by rzelayafavila** [comment]
Yep, I totally agree that there is value in adding that additional explanation to make it as clear as we can to new users.

**Comment by rzelayafavila** [comment]
What do you think about using "varying importance" vs "varying weight", @cgreene?

**Comment by cgreene** [comment]
importance > weight. More meaningful word 😄

**Comment by cgreene** [comment]
`>` used as greater than - not arrow 👍

**Comment by rzelayafavila** [comment]
Ok, cool, I will change this!

**Comment by rzelayafavila** [comment]
Ok, I've changed it: http://165.123.67.154:8000/#/signature/400 Let me know if that (and the styling) looks good!

**Comment by cgreene** [comment]
Feels like maybe having two lines disconnects "filter" from the previous sentence that describes filtering. What about merging those two paragraphs together?

**Comment by rzelayafavila** [comment]
@cgreene I was wondering about that, and couldn't tell which worked better. I'll change it so that they are both in the same paragraph.

**Comment by rzelayafavila** [comment]
Done.

**Comment by cgreene** [comment]
Looks like you may need to edit to remove a linebreak too. Edited in chrome to see what it looked like. Thing together may help to unify that sentence + filter text.
screen shot 2017-07-06 at 11 05 56 am
screen shot 2017-07-06 at 11 06 19 am

Final wording request: `Filter... by` -> `Filter... using`?

**Comment by cgreene** [comment]
"Different methods find" -> "Different methods can be used to find..."

Ok - actual final wording request 😉

**Comment by cgreene** [comment]
With those changes I am 👍 on both interface & code.

**Comment by rzelayafavila** [comment]
@cgreene Ok, I changed it, but now since the bold part is at the end of the sentence, it doesn't appear over the selector when viewing the page in a full window. Do you think this is ok?

**Comment by cgreene** [comment]
I think that bringing it together with the sentence before was more important. Merge at will 👍

**Comment by rzelayafavila** [comment]
Ok!

**Pull request merged**
